image: docker:latest

services:
  - docker:dind

stages:
  - transfer

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: "/certs"

transfer:
  stage: transfer
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_ACCESS_TOKEN $CI_REGISTRY
  tags:
    - docker
  script:
    - docker pull axe007/mauses:v1.0.0
    - docker tag axe007/mauses:v1.0.0 $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  only:
    - tags
    - /^v1.0.2$/
