FROM arm32v7/ubuntu:18.04
MAINTAINER Christian Berger "christian.berger@gu.se"

# Set the env variable DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

ENV QEMU_EXECVE 1
ADD https://raw.githubusercontent.com/chalmers-revere/opendlv-tutorial-kiwi/master/opendlv-perception-helloworld-python/cross-build/cross-build-end /usr/bin/cross-build-end
ADD https://raw.githubusercontent.com/chalmers-revere/opendlv-tutorial-kiwi/master/opendlv-perception-helloworld-python/cross-build/cross-build-start /usr/bin/cross-build-start
ADD https://github.com/chalmers-revere/opendlv-tutorial-kiwi/raw/master/opendlv-perception-helloworld-python/cross-build/qemu-arm-static /usr/bin/qemu-arm-static
ADD https://raw.githubusercontent.com/chalmers-revere/opendlv-tutorial-kiwi/master/opendlv-perception-helloworld-python/cross-build/sh-shim /usr/bin/sh-shim

RUN chmod +x /usr/bin/cross-build-start


RUN apt-get update -y
RUN add-apt-repository ppa:chrberger/libcluon
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y
RUN apt-get install -y --no-install-recommends build-essential python-protobuf python-sysv-ipc python-numpy python-opencv protobuf-compiler libcluon
RUN apt-get clean


ADD ./src /opt/sources
WORKDIR /opt/sources
RUN make

RUN chmod +x /usr/bin/cross-build-end

ENTRYPOINT ["/opt/sources/main.py"]